### PR TITLE
Fixed damage and damage display

### LINKED ISSUE #33: Players always do (odd?) multiples of 5 damage
Player damage is being rounded oddly, you always seem to do a multiple of 5 damage like 25, 35, 45 (can't remember if you can do even multiples like 30 or 40)

### PR DESCRIPTION
**Pull request by theflyingzamboni**
-Damage now rounds correctly
-Correct values are now displayed for floating numbers and d-spell MP costs
Closes #33

### CODE REVIEW

File: src/main/java/legend/game/combat/Bttl_800f.java [hunk 1]
```diff
@@ -4176,8 +4110,8 @@ public static long FUN_800f97d8(final RunningScript a0) {
   }
 
   @Method(0x800f984cL)
-  public static long FUN_800f984c(final RunningScript a0) {
-    FUN_800f4268(a0.params_20.get(0).deref().get(), a0.params_20.get(1).deref().get(), a0.params_20.get(2).deref().get());
+  public static long renderRecover(final RunningScript a0) {
```
Comment (LordMonoxide) [inline src/main/java/legend/game/combat/Bttl_800f.java:4113]: Rename to scriptRenderRecover (it's a script callback)

File: src/main/java/legend/game/combat/Bttl_800c.java [hunk 2]
```diff
@@ -3397,14 +3399,14 @@ public static long FUN_800cca34(final RunningScript s1) {
   }
 
   @Method(0x800ccb3cL)
-  public static long FUN_800ccb3c(final RunningScript a0) {
-    FUN_800f8aa4(a0.params_20.get(0).deref().get(), a0.params_20.get(1).deref().get());
+  public static long renderDamage(final RunningScript a0) {
```
Comment (LordMonoxide) [inline src/main/java/legend/game/combat/Bttl_800c.java:3402]: Rename to scriptRenderDamage

**Review by LordMonoxide — CHANGES_REQUESTED** [review]

**Review by LordMonoxide — APPROVED** [review]
