### PR TITLE
Fix for incorrect SFX downpitch (closes #918)

### LINKED ISSUE #918: Sound effects get pitched down

### PR DESCRIPTION
**Pull request by Illeprih**

### CODE REVIEW

File: src/main/java/legend/game/sound/Sequencer.java [hunk 1]
```diff
@@ -594,26 +594,20 @@ public void sssqTickEffectsOverTime() {
...
-                  } else {
-                    //LAB_8004762c
-                    final int portamentoTimeElapsed = (playingNote.portamentoTimeTotal_64 - playingNote.portamentoTimeRemaining_62) * playingNote.newPortamento_60;
-                    note = playingNote.portamentoNote_4e + portamentoTimeElapsed / 10 / playingNote.portamentoTimeTotal_64;
-                    //TODO remove the *4 by increasing resolution
-                    sixtyFourths = sixtyFourths + (portamentoTimeElapsed * 192 / (playingNote.portamentoTimeTotal_64 * 120) % 16) * 4;
-                  }
+                  final int portamento10ths = playingNote.newPortamento_60;
+                  final int portamentoTimeElapsed = playingNote.portamentoTimeTotal_64 - playingNote.portamentoTimeRemaining_62;
+                  final float fraction = (portamento10ths * portamentoTimeElapsed) / (playingNote.portamentoTimeTotal_64 * 10f);
```
Comment (LordMonoxide) [inline src/main/java/legend/game/sound/Sequencer.java:607]:
```suggestion
                  final float fraction = (portamento10ths * portamentoTimeElapsed) / (playingNote.portamentoTimeTotal_64 * 10.0f);
```

**Review by LordMonoxide — APPROVED** [review]
