### PR TITLE
Fix for menu addition values (closes #2659)

### LINKED ISSUE #2659: Omni-Sweep and Cat's Cradle Damage in Addition Menu Differing from Retail
In retail the damage is 501% for Omni-Sweep but in SC it is showing as 500%. Also happening for Cat's Cradle which normally deals 351% but appears as 350% here.

Retail:
Image

SC:
Image

Retail: 
Image

SC:
Image

### PR DESCRIPTION
**Pull request by Illeprih**
The issue is caused by float math.
There are multiple += hit * multi, since the value is floored at the end, this compounds the float imprecision enough to shift it slightly below the actual value.

### CODE REVIEW

File: src/main/java/legend/game/additions/SimpleAddition.java [hunk 1]
```diff
@@ -18,10 +18,10 @@ public int getDamage(final GameState52c state, final CharacterData2c charData, f
     float damage = 0;
```
Comment (LordMonoxide) [inline src/main/java/legend/game/additions/SimpleAddition.java]: Should change this to `int` since we're just accumulating int values now

**Review by LordMonoxide — APPROVED** [review]
