### PR TITLE
[#15] Use direct CDROM methods (closes #15)

### LINKED ISSUE #15: Invalid CDROM sync code when booting
There's a very common exception when booting, probably about 5-10% of the time, especially on slower hardware. The solution will probably be to just rewrite the code reading these files so that it doesn't have to rely on the hardware translation layer.

```
java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
	at legend.core.cdrom.SyncCode.fromLong(SyncCode.java:14)
	at legend.game.Scus94491BpeSegment_8003.processCdromInterrupt(Scus94491BpeSegment_8003.java:789)
	at legend.game.Scus94491BpeSegment_8003.FUN_800321c4(Scus94491BpeSegment_8003.java:1065)
	at legend.game.Scus94491BpeSegment_8003.FUN_80036e50(Scus94491BpeSegment_8003.java:3444)
	at legend.game.Scus94491BpeSegment_8003.FUN_8003429c(Scus94491BpeSegment_8003.java:2027)
	at legend.game.SInit.FUN_800fbb9c(SInit.java:219)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:362)
	at legend.core.memory.types.SupplierRef.run(SupplierRef.java:25)
	at legend.game.SInit.executeSInitLoadingStage(SInit.java:94)
	at legend.game.Scus94491BpeSegment_800e.executeSInitLoadingStages(Scus94491BpeSegment_800e.java:1053)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:362)
	at legend.core.memory.types.RunnableRef.run(RunnableRef.java:17)
	at legend.game.Scus94491BpeSegment_800e.executePregameLoadingStage(Scus94491BpeSegment_800e.java:934)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:362)
	at legend.core.memory.types.RunnableRef.run(RunnableRef.java:17)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:388)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$0(Scus94491BpeSegment.java:354)
	at legend.core.gpu.Gpu.lambda$run$11(Gpu.java:451)
	at legend.core.opengl.Context.draw(Context.java:96)
	at legend.core.opengl.Window$Events.onDraw(Window.java:336)
	at legend.core.opengl.Window.run(Window.java:217)
	at legend.core.gpu.Gpu.run(Gpu.java:458)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by LordMonoxide**
Makes a lot of the CDROM code interact directly with the CDROM emulator instead of communicating via registers. It's faster and fixes desyncs during concurrency. This should fix the fairly common crash on startup.

### CODE REVIEW

File: src/main/java/legend/game/Scus94491BpeSegment_8003.java [hunk 1]
```diff
@@ -807,57 +805,43 @@ public static long processCdromInterrupt() {
...
+    CDROM.enableInterrupts(0x7L); // Enable interrupts
 
     if(syncCode != SyncCode.ACKNOWLEDGE || _80053108.get(previousCdromCommand_80052f61.get().command).get() != 0) {
       //LAB_80031b30
+      //LAB_80031b74
+      // error, seek error, ID error, or shell open
+      final long errors = results[0] & 0b1_1101L;
+
+      if(errors != 0) {
+        throw new RuntimeException("CDROM errors " + Long.toHexString(errors));
```
Comment (LordMonoxide) [inline src/main/java/legend/game/Scus94491BpeSegment_8003.java:822]: Updated error handling to fail outright and removed all error handling code below. We don't have to worry about dirty disks or open disk drives.

File: src/main/java/legend/game/SStrm.java [hunk 2]
```diff
@@ -337,9 +337,11 @@ public static void stopFmv(final long a0) {
     disableCdromDmaCallbacksAndClearDataFifo();
 
     //LAB_800fbf88
-    while(!DsControl(CdlCOMMAND.PAUSE_09, 0, 0)) {
-      DebugHelper.sleep(1);
-    }
+    CDROM.sendCommand(CdlCOMMAND.PAUSE_09);
+    CDROM.acknowledgeInterrupts();
+//    while(!DsControl(CdlCOMMAND.PAUSE_09, 0, 0)) {
```
Comment (angelocali) [inline src/main/java/legend/game/SStrm.java:342]: Shall we remove the outcommented code? We can restore it from the repository if needed.

**Review by angelocali — COMMENTED** [review]
LGTM! Maybe we could remove the outcommented code if not needed anymore.

File: src/main/java/legend/game/SStrm.java (hunk 2 above)
Comment (LordMonoxide) [reply src/main/java/legend/game/SStrm.java:342]: Yeah, I like to keep some original code around for reference, but these are so simple we can just remove them
