### PR TITLE
Fix HP/MP not being right-aligned (closes #446)

### LINKED ISSUE #446: HP/MP should be right-aligned in combat menu

### PR DESCRIPTION
**Pull request by LordMonoxide**

### CODE REVIEW

File: src/main/java/legend/game/combat/Bttl_800f.java [hunk 1]
```diff
@@ -277,29 +277,24 @@ public static void renderNumber(final int charSlot, final int a1, int value, fin
...
         struct.x_02 = _800c7014.get(a1 * 2).get() + i * 5;
       } else {
-        struct.x_02 = _800c7014.get(a1 * 2).get() + a2_0 * 5;
+        struct.x_02 = _800c7014.get(a1 * 2).get() + (i + rightAlignOffset) * 5;
       }
 
       //LAB_800f1920
       struct.y_04 = _800c7014.get(a1 * 2 + 1).get();
-      struct.u_06 = _800c7028.get(sp0x00[a2_0]).get();
+      struct.u_06 = _800c7028.get(sp0x00[i]).get();
```
Comment (Ink230) [inline src/main/java/legend/game/combat/Bttl_800f.java:297]: \- cookie points for not renaming _800c7028, _800c7014

**Review by Ink230 — APPROVED** [review]

File: src/main/java/legend/game/combat/Bttl_800f.java (hunk 1 above)
Comment (LordMonoxide) [reply src/main/java/legend/game/combat/Bttl_800f.java]: Updated
